### ISSUE TITLE
I got error when starting to fuzz a sample project

### ISSUE THREAD

**Issue by erfanwakka** [ChainSecurity/ChainFuzz#2]
When I try to fuzz the provided project I got this error : 
```
Done. Time to run:  ./build/bin/fuzzer --metadata /shared//fuzz_config/metadata_9e0c05b73214e684174ce8438f8dd1fb4deba2da.json --limit 10000
root@f4e25504c4a3:/go/src/fuzzer# ./build/bin/fuzzer --metadata /shared/fuzz_config/metadata_*.json --limit 4000
WARN [04-04|05:58:07.240] Contract was not provided (you can use --contract option)
INFO [04-04|05:58:07.382] Persisted trie from memory database      nodes=0 size=0.00B time=3.277µs gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [04-04|05:58:07.399] Loaded most recent local header          number=0 hash=6116de…ed79cc td=0 age=49y11mo2w
INFO [04-04|05:58:07.399] Loaded most recent local full block      number=0 hash=6116de…ed79cc td=0 age=49y11mo2w
INFO [04-04|05:58:07.399] Loaded most recent local fast block      number=0 hash=6116de…ed79cc td=0 age=49y11mo2w
INFO [04-04|05:58:07.400] Imported new chain segment               blocks=1 txs=0 mgas=0.000 elapsed=149.22µs mgasps=0.000 number=1 hash=dec19d…8e11e7 age=49y11mo2w dirty=212.00B
panic: error unmarshalling transaction: json: cannot unmarshal string into Go struct field transaction.gas of type uint64


goroutine 1 [running]:
fuzzer/utils.ReadTransactions(0xc4200b0230, 0x4f, 0x0, 0x0, 0x0)
	/go/src/fuzzer/utils/transactions.go:121 +0x45a
fuzzer/utils.NewBackend(0x7ffe3c8358a1, 0x4a, 0xc42009e690, 0xc42008d8c0)
	/go/src/fuzzer/utils/backend.go:183 +0x4cc
main.fuzz(0xc420104580)
	/go/src/fuzzer/fuzzer/fuzzer.go:170 +0x83
main.run(0xc420104580, 0x0, 0x0)
	/go/src/fuzzer/fuzzer/fuzzer.go:264 +0x14c
fuzzer/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0x854e80, 0x915730, 0xc420104580, 0xc4200c6540, 0x0)
	/go/src/fuzzer/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xc8
fuzzer/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc4200b89c0, 0xc42009e0f0, 0x5, 0x5, 0x0, 0x0)
	/go/src/fuzzer/vendor/gopkg.in/urfave/cli.v1/app.go:264 +0x5ee
main.main()
	/go/src/fuzzer/fuzzer/fuzzer.go:282 +0x55
root@f4e25504c4a3:/go/src/fuzzer#
```

**Comment by pandabox-dev** [comment]
@erfanwakka I got this error too. Have you solved this problem yet?
